# How often to collect metrics which is 1 second = 1000ms
sample.interval.ms=1000

# How many samples to keep in memory which is 600 = 10 minutes
store.capacity=600

#CPUAlert - Trigger if current exceeds average by 30.0
cpu.spike.delta=30.0

#CPUAlert - Spike must last 3 seconds
cpu.spike.seconds=3

#RAM Alert - Trigger if RAM increases 5.0 over 60 seconds
ram.rise.threshold=5.0

#Alert Cooldown - Wait 10000ms long between same alert (10 seconds)
alert.cooldown.ms=10000

#HTTP API port
api.port=8080

#CSV Export settings
export.csv.enabled=true
export.csv.path=metrics.csv
export.csv.flushEvery=5